=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"shortName": {
				"type": "string"
			},
			"name": {
				"type": "string"
			},
			"start": {
              "oneOf": [{
				"type": "string",
				"format": "date"
              },
              {
				"type": "string",
      			"pattern": "^[0-9]{4}$"
              }]
			},
			"end": {
              "oneOf": [{
				"type": "string",
				"format": "date"
              },
              {
				"type": "string",
      			"pattern": "^[0-9]{4}$"
              }]
			},
			"deadline": {
				"oneOf": [{
						"type": "string",
						"maxLength": 0
					},
					{
						"type": "string",
						"format": "date"
					}
				]
			},
			"city": {
				"type": "string"
			},
			"country": {
				"type": "string"
			},
			"link": {
				"oneOf": [{
						"type": "string",
						"maxLength": 0
					},
					{
						"type": "string",
						"format": "uri"
					}
				]
			},
			"addressLink": {
				"oneOf": [{
						"type": "string",
						"maxLength": 0
					},
					{
						"type": "string",
						"format": "uri"
					}
				]
			},
			"type": {
				"oneOf": [{
						"type": "string",
						"maxLength": 0
					},
					{
						"enum": ["Conference", "Workshop", "School"]
					}
				]
			},
			"note": {
				"type": "string"
			},
			"cost": {
				"type": "string",
                "maxLength": 20
			},
			"costNote": {
				"type": "string",
                "maxLength": 100
            }
		},
		"additionalProperties": false,
		"required": ["shortName", "name", "start", "end", "city", "country", "type"]
	}
}

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/conf2025.json
[
  {
    "shortName": "SII",
    "name": "IEEE/SICE International Symposium on System Integration",
    "start": "2025-01-21",
    "end": "2025-01-24",
    "deadline": "",
    "city": "Munich",
    "country": "Germany",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "HRI",
    "name": "ACM/IEEE International Conference on Human-Robot Interaction",
    "start": "2025-03-03",
    "end": "2025-03-06",
    "deadline": "",
    "city": "South Wharf, VIC",
    "country": "Australia",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "ICRA",
    "name": "IEEE International Conference on Robotics and Automation",
    "start": "2025-05-17",
    "end": "2025-05-23",
    "deadline": "",
    "city": "Atlanta",
    "country": "USA",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "CASE",
    "name": "IEEE International Conference on Automation Science and Engineering",
    "start": "2025-08-18",
    "end": "2025-08-22",
    "deadline": "",
    "city": "Anaheim, CA",
    "country": "USA",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/conf2027.json
[
  {
    "shortName": "ICRA",
    "name": "IEEE International Conference on Robotics and Automation",
    "start": "2027",
    "end": "2027",
    "deadline": "",
    "city": "Seoul",
    "country": "South Korea",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/school2025.json
[
    {
        "shortName": "EECI-IGS",
        "name": "EECI-IGS various summer schools",
        "start": "2025-01-01",
        "end": "2025-07-07",
        "deadline": "",
        "city": "various",
        "country": "European Union",
        "link": "http://www.eeci-igsc.eu/",
        "type": "School",
        "cost": "€350-€800",
        "costNote": "academics/industrial early(late) : €350(450)/€600(800). 150€ low education priority countries", 
        "addressLink": "",
        "note": "Check website, schools are many and different"
    },
    {
        "shortName": "RVSS",
        "name": "Robotic Vision Summer School",
        "start": "2025-02-03",
        "end": "2025-02-08",
        "deadline": "2025-01-15",
        "city": "Kioloa",
        "country": "Australia",
        "link": "https://www.rvss.org.au/",
        "type": "School",
        "cost": "$990-$4500",
        "costNote": "students/industry: AUD 990/4500", 
        "addressLink": "https://maps.app.goo.gl/Zeq8NhEoAVM2jXHL6",
        "note": "The Australian Centre for Robotic Vision presents the Robotic Vision Summer School (RVSS), hosted in-person at the Australian National University (ANU) Kioloa coastal campus. The ability to see is the remaining technological roadblock to the ubiquitous deployment of robots into society. RVSS provides a premium venue for graduate students and industry researchers to learn about fundamental and advanced topics in computer vision and robotics. The summer school also provides a unique opportunity to experiment with computer vision algorithms on actual robotic hardware."
    },
    {
        "shortName": "INVICTA",
        "name": "INVICTA Summer School",
        "start": "2025-04-07",
        "end": "2025-04-11",
        "deadline": "2025-03-24",
        "city": "Porto",
        "country": "Portugal",
        "link": "https://invicta.inesctec.pt/",
        "type": "School",
        "cost": "€650-€750",
        "costNote": "early/regular/late : €650/700/750", 
        "addressLink": "https://maps.app.goo.gl/scrGbsSxrSLViCnEA",
        "note": "The INvicta school of VIsion, Computational intelligence, and patTern Analysis - INVICTA - is a school of artificial intelligence, computer vision and pattern analysis organised by the Visual Computing and Machine Intelligence - VCMI - group of the Centre for Telecommunications and Multimedia - CTM - of the INESC TEC. INVICTA will guide you through an unforgettable journey into the development of intelligent systems, where innovation meets tradition in the captivating city of Porto."
    },
    {
        "shortName": "NENGO",
        "name": "Nengo Summer School",
        "start": "2025-06-01",
        "end": "2025-06-13",
        "deadline": "2025-02-01",
        "city": "Ontario",
        "country": "Canada",
        "link": "https://www.nengo.ai/summer-school/",
        "type": "School",
        "cost": "$550-1000",
        "costNote": "academic/industry: $550/1000", 
        "addressLink": "https://maps.app.goo.gl/fazAfFEXPhkNWzjh7",
        "note": "The Centre for Theoretical Neuroscience at the University of Waterloo is excited to announce our 10th annual Nengo summer school on large-scale brain modelling and neuromorphic computing. As a recurring special feature of the school, participants will be given on-site access to neuromorphic hardware, including Stanford’s mixed digital/analog chip Braindrop, the SpiNNaker chip, and a variety of FPGAs."
    },
    {
        "shortName": "AICET",
        "name": "AIDA AI/ML cutting edge trends Symposium and Summer School",
        "start": "2025-07-07",
        "end": "2025-07-11",
        "deadline": "",
        "city": "Thessaloniki",
        "country": "Greece",
        "link": "https://icarus.csd.auth.gr/aida-auth-ai-cutting-edge-trends-aicet2025-summer-symposium-and-school/",
        "type": "School",
        "cost": "TBD",
        "costNote": "",
        "addressLink": "https://maps.app.goo.gl/X6tXMqpDoexKa9VE9",
        "note": "Artificial Intelligence (AI), and Machine Learning (ML) in particular, advance very rapidly, at  a pace that even specialists have difficulties in following it. Its impact, particularly through Large Language Models and Generative AI affect almost all scientific disciplines. AI has a huge social impact, e.g., on education, labor market, politics and governance.  Given the fast AI evolution, both industry and academia are interested in fast personnel reskilling and upskilling on AI edge technologies. This event, co-organized by International AI Doctoral Academy (AIDA)  and AUTH,  will cater these advanced AI education needs."
    }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/school2024.json
[
  {
    "name": " Social Robotics, Artificial Intelligence & Multimedia Winter School",
    "deadline": "",
    "city": "Grenoble",
    "country": "France",
    "link": "https://spring-h2020.eu/soraim/",
    "type": "School",
    "shortName": "SoRAIM",
    "start": "2024-02-19",
    "end": "2024-02-23",
    "cost": "free",
    "costNote": "", 
    "addressLink": "https://maps.app.goo.gl/5kz6BJdDRhCbRigZ7",
    "note": "The SoRAIM multi-disciplinary winter school combines topics in social robotics, artificial intelligence, and multimedia. Several top-level invited speakers will introduce and discuss all relevant areas for building socially aware robots that communicate and interact with humans in a shared space."
  },
  {
    "name": "Machine Learning Summer School",
    "deadline": "2024-09-30",
    "city": "Ginowan",
    "country": "Japan",
    "link": "https://groups.oist.jp/mlss",
    "type": "School",
    "shortName": "MLSS",
    "start": "2024-03-04",
    "end": "2024-03-15",
    "cost": "JPY50000-150000",
    "costNote": "students/academics/professional : JPY50000/100000/150000", 
    "addressLink": "https://goo.gl/maps/hZEUAq2dqm8LkVMd7",
    "note": "The machine learning summer school (MLSS) series was started in 2002 with the motivation to promulgate modern methods of statistical machine learning and inference. It was motivated by the observation that while many students are keen to learn about machine learning, and an increasing number of researchers want to apply machine learning methods to their research problems, only few machine learning courses are taught at universities. Machine learning summer schools present topics which are at the core of modern Machine Learning, from fundamentals to state-of-the-art practice. The speakers are leading experts in their field who talk with enthusiasm about their subjects."
  },
  {
    "shortName": "ACDL",
    "name": "Advanced Course on Data Science & Machine Learning",
    "deadline": "2024-02-23",
    "city": "Castiglione della Pescaia",
    "country": "Italy",
    "link": "https://acdl2024.icas.events/",
    "type": "School",
    "start": "2024-06-10",
    "end": "2024-06-14",
    "cost": "€580-630",
    "costNote": "early:580€, late:630€", 
    "addressLink": "https://maps.app.goo.gl/SgTWWKTTyStMvpZM7",
    "note": "The Course provides a stimulating environment for junior academics, early career researches, Post-Docs, PhD students and industry leaders (and highly motivated, promising and brilliant Master students). Participants will also have the chance to present their results with talks, and to interact with their colleagues, in a convivial, professional and productive environment."
  }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/conf2026.json
[
  {
    "shortName": "SII",
    "name": "IEEE/SICE International Symposium on System Integration",
    "start": "2026-01-11",
    "end": "2026-01-14",
    "deadline": "2025-08-01",
    "city": "Cancun",
    "country": "Mexico",
    "link": "https://sice-si.org/SII2026/",
    "type": "Conference",
    "addressLink": "https://maps.app.goo.gl/JmuB7wzPvWgmtm6R8",
    "note": "IEEE/SICE SII is the premier symposium series presenting the state-of-the-art and future perspectives of system integration, where academic researchers and industry experts share ideas and experiences surrounding frontier technologies, research breakthroughs, and innovative solutions and applications."
  },
  {
    "shortName": "ERF",
    "name": "European Robotics Forum",
    "start": "2026-03-23",
    "end": "2026-03-26",
    "deadline": "",
    "city": "Stavanger",
    "country": "Norway",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "ICRA",
    "name": "IEEE International Conference on Robotics and Automation",
    "start": "2026-06-01",
    "end": "2026-06-05",
    "deadline": "",
    "city": "Wien",
    "country": "Austria",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "AIM",
    "name": "IEEE/ASME International Conference on Advanced Intelligent Mechatronics",
    "start": "2026-07-07",
    "end": "2026-07-11",
    "deadline": "",
    "city": "Genova",
    "country": "Italy",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "AUV",
    "name": "IEEE OES AUV",
    "start": "2026-09-01",
    "end": "2026-09-03",
    "deadline": "",
    "city": "Southampton",
    "country": "UK",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "EHAPTICS",
    "name": "Eurohaptics",
    "start": "2026",
    "end": "2026",
    "deadline": "",
    "city": "Siena",
    "country": "Italy",
    "link": "https://eurohaptics.org/ehc2026/",
    "type": "Conference",
    "addressLink": "https://g.co/kgs/UqiUpmV",
    "note": ""
  },
  {
    "shortName": "IROS",
    "name": "IEEE/RSJ International Conference on Intelligent Robots and Systems",
    "start": "2026",
    "end": "2026",
    "deadline": "",
    "city": "TBD",
    "country": "USA",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  },
  {
    "shortName": "BioRob",
    "name": "11th IEEE RAS/EMBS International Conference on Biomedical Robotics and Biomechatronics",
    "start": "2026-08-01",
    "end": "2026-08-04",
    "deadline": "",
    "city": "Edmonton",
    "country": "Canada",
    "link": "",
    "type": "Conference",
    "addressLink": "",
    "note": ""
  }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/school2023.json
[
  {
    "name": "Latin American Summer School on Cognitive Robotics",
    "deadline": "",
    "city": "Santiago",
    "country": "Chile",
    "link": "https://lacoro.org/",
    "type": "School",
    "shortName": "LACORO",
    "start": "2023-01-03",
    "end": "2023-01-06",
    "addressLink": "https://goo.gl/maps/pZbpNurtMicUNs5m8",
    "note": ""
  },
  {
    "name": "EECI-IGS various summer schools",
    "deadline": "",
    "city": "various",
    "country": "",
    "link": "http://www.eeci-igsc.eu/doc/users/975/bib/2022-2023/eeciigsc2023programfinal.pdf",
    "type": "School",
    "shortName": "EECI-IGS",
    "start": "2023-02-01",
    "end": "2023-03-30",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "DeepLearn Winter",
    "deadline": "",
    "city": "Bournemouth",
    "country": "UK",
    "link": "https://irdta.eu/deeplearn/2023wi/",
    "type": "School",
    "shortName": "DLWI",
    "start": "2023-01-17",
    "end": "2023-01-21",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "EECI-IGS various summer schools",
    "deadline": "2023-03-19",
    "city": "various",
    "country": "",
    "link": "http://www.eeci-igsc.eu/doc/users/975/bib/2022-2023/eeciigsc2023programfinal.pdf",
    "type": "School",
    "shortName": "EECI-IGS",
    "start": "2023-04-01",
    "end": "2023-06-30",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "Spring school on Mechanical aspects and applications of Haptics",
    "deadline": "",
    "city": "La Valletta",
    "country": "Malta",
    "link": "https://www.intuitive-itn.eu",
    "type": "School",
    "shortName": "INT",
    "start": "2023-04-17",
    "end": "2023-04-21",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "IFToMM Italy International Summer School On Human-Centred Robotics.",
    "deadline": "2023-05-15",
    "city": "Ancona",
    "country": "Italy",
    "link": "https://human.univpm.it/human/",
    "type": "School",
    "shortName": "HCR",
    "start": "2023-06-26",
    "end": "2023-06-30",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "EECI-IGSC Learning-based predictive control",
    "deadline": "",
    "city": "Zurich",
    "country": "Switzerland",
    "link": "http://www.eeci-igsc.eu/",
    "type": "School",
    "shortName": "EECI-IGSC",
    "start": "2023-06-26",
    "end": "2023-06-30",
    "addressLink": "https://eeciigsc.web-events.fr//doc/users/975/bib/2022-2023/m22eeciethzurichlogisticalinformation.pdf",
    "note": "Learning-based Model Predictive Control (MPC) provides advanced control systems with the capability to exploit real-time collected information to improve performance in face of uncertainty, at the same time maintaining high safety standards. This is a crucial requirement of next generation control applications, such as autonomous passenger cars, or autonomous aerial, marine and ground drones for civil applications. In established industrial systems, such a capability can also bring significant benefits, reducing commissioning time and cost, and the effects of product/process variability. After a brief review of fundamentals of MPC, the course presents an overview of existing learning-based MPC methods, followed by a deep-dive into theory and applications of selected techniques for different problem settings. These include stochastic and unknown-but-bounded uncertainty, and reactive techniques. A discussion on advanced topics and active research directions concludes the module."
  },
  {
    "name": "Summer School on Multi-robot systems",
    "deadline": "",
    "city": "Prague",
    "country": "Czech Republic",
    "link": "http://mrs.felk.cvut.cz/summer-school-2023/",
    "type": "School",
    "shortName": "RASPRAGUE",
    "start": "2023-07-03",
    "end": "2023-07-07",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "ETH Robotics Summer School",
    "deadline": "2023-03-24",
    "city": "Geneva",
    "country": "Switzerland",
    "link": "https://robotics-summerschool.ethz.ch/",
    "type": "School",
    "shortName": "ETHRSS",
    "start": "2023-07-09",
    "end": "2023-07-14",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "International Computer Vision Summer School",
    "deadline": "2023-03-31",
    "city": "Punta Sampieri - Scicli",
    "country": "Italy",
    "link": "https://iplab.dmi.unict.it/icvss2023/",
    "type": "School",
    "shortName": "ICVSS",
    "start": "2023-07-09",
    "end": "2023-07-15",
    "addressLink": "https://goo.gl/maps/BhybXuThQugcoTMM6",
    "note": "The seventeenth edition of the International Computer Vision Summer School aims to provide both an objective and clear overview and an in-depth analysis of the state-of-the-art research in Computer Vision. The last decade has seen a revolution in the theory and application of computer vision and machine learning. The next decade will see machine perception in embodied systems which learn representations for and from action and interaction."
  },
  {
    "name": "Machine Learning Summer School",
    "deadline": "2023-05-15",
    "city": "Lisbon",
    "country": "Portugal",
    "link": "http://lxmls.it.pt/2023/",
    "type": "School",
    "shortName": "LML",
    "start": "2023-07-14",
    "end": "2023-07-20",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "ELLIS Summer School on Probabilistic Machine Learning - Cambridge Unit",
    "deadline": "",
    "city": "Cambridge ",
    "country": "United Kingdom",
    "link": "https://ellis.eu/events/ellis-summer-school-on-probabilistic-machine-learning-cambridge-unit",
    "type": "School",
    "shortName": "ELLIS",
    "start": "2023-07-17",
    "end": "2023-07-21",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "Embodied Intelligence â€“ Perception and Learning in Nature and Robotics",
    "deadline": "2023-03-31",
    "city": "Berlin",
    "country": "Germany",
    "link": "https://www.scienceofintelligence.de/summerschool/",
    "type": "School",
    "shortName": "SCIoI-ISAB",
    "start": "2023-08-21",
    "end": "2023-08-25",
    "addressLink": "https://goo.gl/maps/d5hisGN9u2A7FxTb8",
    "note": "In this summer school at the Excellence Cluster Science of Intelligence in Berlin, we would like to explore alternative paths towards efficient and sustainable robot perception and learning: efficient AI for individual artificial agents and teams. Inspired by insights of biologically intelligent systems (e.g. ant colonies, fish schools, and honey bees) AI has been going through immense progress. Efforts range from discovering simple yet efficient behavioral principles that allow solving complex tasks, to novel biologically inspired technological developments, such as event-based cameras, which open novel opportunities for efficient robot perception."
  },
  {
    "name": "Mediterranean Machine Learning Summer School",
    "deadline": "2023-02-28",
    "city": "Thessaloniki",
    "country": "Greece",
    "link": "https://www.m2lschool.org/",
    "type": "School",
    "shortName": "MML",
    "start": "2023-08-28",
    "end": "2023-09-02",
    "addressLink": "https://goo.gl/maps/4XGrk9ZeDJ38m22p9",
    "note": ""
  },
  {
    "name": "Summer School on Singularities of Mechanisms and Robotic Manipulators",
    "deadline": "2023-07-31",
    "city": "Nantes",
    "country": "France",
    "link": "https://www.simero.org/index.php",
    "type": "School",
    "shortName": "SIMERO",
    "start": "2023-09-18",
    "end": "2023-09-22",
    "addressLink": "",
    "note": ""
  }
]

=== mattiadutto/AwesomeRoboticsConferencesAndSchoolsList/www/data/school2022.json
[
  {
    "name": "Summer School Deformations in Robotics",
    "deadline": "",
    "city": "Villeneuve d’Ascq (Lille)",
    "country": "France",
    "link": "https://defrobotics2022.sciencesconf.org/",
    "type": "School",
    "shortName": "DEF",
    "start": "2022-07-04",
    "end": "2022-07-08",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "EECI-IGS various summer schools",
    "deadline": "",
    "city": "Zurich",
    "country": "Swiss",
    "link": "http://www.eeci-igsc.eu/",
    "type": "School",
    "shortName": "EECIIGS",
    "start": "2022-07-11",
    "end": "2022-07-15",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "Deep Learning Summer School",
    "deadline": "",
    "city": "Las Palmas de Gran Canaria",
    "country": "Spain",
    "link": "https://irdta.eu/deeplearn/2022su/",
    "type": "School",
    "shortName": "DLSU",
    "start": "2022-07-25",
    "end": "2022-07-29",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "IEEE RAS Summer School",
    "deadline": "",
    "city": "Praga",
    "country": "Czech",
    "link": "http://mrs.felk.cvut.cz/summer-school-2022/",
    "type": "School",
    "shortName": "RASSS",
    "start": "2022-09-01",
    "end": "2022-09-05",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "Summer School on Service-Based and Cloud Robotics",
    "deadline": "",
    "city": "Palma de Majorca",
    "country": "Spain",
    "link": "",
    "type": "School",
    "shortName": "SBCR",
    "start": "2022-09-20",
    "end": "2022-09-22",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "DeepLearn 2022 Autumn",
    "deadline": "",
    "city": "Luleå",
    "country": "Sweden",
    "link": "https://irdta.eu/deeplearn/2022au/",
    "type": "School",
    "shortName": "DLAU",
    "start": "2022-10-17",
    "end": "2022-10-21",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "1ère Edition de l'Ecole du GT8 Apprentissage et Neurosciences pour la Robotique ",
    "deadline": "",
    "city": "Moliets et Maa (Landes)",
    "country": "France",
    "link": "https://sites.google.com/view/ecoledugt8/accueil",
    "type": "School",
    "shortName": "ANR",
    "start": "2022-10-20",
    "end": "2022-10-23",
    "addressLink": "",
    "note": ""
  },
  {
    "name": "Surgical Imaging and Vision WINTER SCHOOL",
    "deadline": "",
    "city": "London",
    "country": "UK",
    "link": "https://www.imperial.ac.uk/hamlyn-centre/names--global-engagement/hamlyn-winter-school-on-surgical-imaging-and-vision/",
    "type": "School",
    "shortName": "SIV",
    "start": "2022-12-05",
    "end": "2022-12-09",
    "addressLink": "",
    "note": ""
  }
]
